### ISSUE TITLE
UC: Dynamic adjustment to the route because of real time date

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#200]
**Summary**
If there are relevant real time data like a disruption (delay, cancellation, ...) on a service that's part of my route planned, my route should be adjusted dynamically.

**Depends on**

- 

**Subtasks**
- [ ] regulary fetch real time data of services on route (live arrival/departure, platform, further status information like line closures, signal faults, ... - for NRW/VRR such information are mostly published on [zuginfo.nrw](https://zuginfo.nrw/) as far as I know)
- [ ] check if the planned route is still possible / changeovers are getting tight (in a time manner)
- [ ] search for alternative routes that are better (faster) then the current one (or to avoid possibly growing problems on current route) 
- [ ] dynamically adjust the route the user is travelling on
