### ISSUE TITLE
UC: Notification, if a change to the planned route might occur / be needed

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#202]
**Summary**
If real time data suggest 

**Depends on**

- issue

**Subtasks**

- [ ] regulary fetch real time data of services on route (live arrival/departure, platform, further status information like line closures, signal faults, ... - for NRW/VRR such information are mostly published on [zuginfo.nrw](https://zuginfo.nrw) as far as I know) 
- [ ] check if the planned route is still possible / changeovers are getting tight (in a time manner)
- [ ] show user notification about new real time data (What has changed? What does it mean for the route the user is travelling on?)
