### ISSUE TITLE
UC: Monitor real time data / further status information of the current route

### ISSUE THREAD

**Issue by JaJako** [Oeffis/Oeffis#207]
**Summary**
All relevant real time data (and further status information) should be included in planning and navigating my route, so that adjustments are possible.

**Depends on**
/

**Subtasks**
- [ ] regulary fetch real time data of services on route (live arrival/departure, platform, further status information like line closures, signal faults, ... - for NRW/VRR such information are mostly published on [zuginfo.nrw](https://zuginfo.nrw) as far as I know) 
- [ ] check if the planned route is still possible / changeovers are getting tight (in a time manner)
- [ ] recalculate / replan route
