### ISSUE TITLE
UC: Show probabilities of a delay happening (based on historical train data)

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#209]
The app should show the routes with a special rating, percentage or color to represent the calculated probabilities and occurrences of delays based on historical train data.

```[tasklist]
### Tasks
- [ ] https://github.com/Oeffis/Oeffis/issues/297
- [ ] https://github.com/Oeffis/Oeffis/issues/350
- [ ] #379
- [ ] #380
- [ ] https://github.com/Oeffis/Oeffis/issues/384
- [ ] https://github.com/Oeffis/Oeffis/issues/348
- [ ] #383
- [ ] #382
- [ ] https://github.com/Oeffis/Oeffis/issues/437
```
