### ISSUE TITLE
UC: Show alternative route suggestions based on delay train data

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#211]
The route suggestions should be adjusted depending on calculated train delay data and therefore moved in priority inside the list.

```[tasklist]
### Tasks
- [ ] https://github.com/Oeffis/Oeffis/issues/297
- [ ] https://github.com/Oeffis/Oeffis/issues/379
- [ ] https://github.com/Oeffis/Oeffis/issues/381
```
