### ISSUE TITLE
UC: Advise optimal departure times for the less probability of delay

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#213]
Using the calculated delay probabilities aswell as optimal route times, the user should be recommended an optimal departure time, which may or may not be the first in line after the input time.

```[tasklist]
### Tasks
- [ ] https://github.com/Oeffis/Oeffis/issues/297
- [ ] https://github.com/Oeffis/Oeffis/issues/379
- [ ] Get input departure time
- [ ] Calculate routes of least resistance aswell as fastest routes
- [ ] Recommend optional faster or more comfortable routes than the first route in line of time
```
