### ISSUE TITLE
Get historical train data

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#297]
```[tasklist]
### Tasks
- [ ] https://github.com/Oeffis/Oeffis/issues/298
- [ ] https://github.com/Oeffis/Oeffis/issues/311
- [ ] https://github.com/Oeffis/Oeffis/issues/313
- [ ] https://github.com/Oeffis/Oeffis/issues/308
- [ ] https://github.com/Oeffis/Oeffis/issues/309
- [ ] https://github.com/Oeffis/Oeffis/issues/314
- [ ] https://github.com/Oeffis/Oeffis/issues/315
```

**Comment by JaJako** [comment]
Time spent: 1 hour

Setting up local postgres db for collected historic data.

**Comment by JaJako** [comment]
> > Setting up local postgres db for collected historic data.
> 
> Did you see that there was a docker-compose file you could use?

Yes, after despairing over setting up some local postgres and figuring out how to import the data for far too long, I noticed your issue and commits that are linked above in here. At least I got it working manually, but the docker-compose file is way easier (what a surprise 🙃). Now also using the docker-compose setup.

**Comment by Paulomart** [comment]
Sorry about this. I will adjust the documentation.

**Comment by JaJako** [comment]
Time spent: 30 minutes

Defining new issues (meeting 27.10.23).
