### ISSUE TITLE
Add functionality to origin/destination toggle button

### ISSUE THREAD

**Issue by AconexOfficial** [Oeffis/Oeffis#419]
```[tasklist]
### Tasks
- [x] Add swap id functionality
- [x] Check if location swap is needed
- [x] Test functionality
- [x] Added location swap
- [x] Add functionality to modal taking in different location
- [x] Add map adjustment functionality to toggle
- [x] Save written text instead of selected station name
```

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

Working on modals getting location names from route planner

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes

Save written text of searchbar for every modal each

**Comment by AconexOfficial** [comment]
Time spent: 1 hour

**Comment by AconexOfficial** [comment]
Time spent: 30 minutes
